return {
    ["ev"] = ControlCommandType.EvalStart,
    ["out"] = ControlCommandType.EvalOutput,
    ["/ev"] = ControlCommandType.EvalEnd,
    ["du"] = ControlCommandType.Duplicate,
    ["pop"] = ControlCommandType.PopEvaluatedValue,
    ["~ret"] = ControlCommandType.PopFunction,
    ["->->"] = ControlCommandType.PopTunnel,
    ["str"] = ControlCommandType.BeginString,
    ["/str"] = ControlCommandType.EndString,
    ["nop"] = ControlCommandType.NoOp,
    ["choiceCnt"] = ControlCommandType.ChoiceCount,
    ["turn"] = ControlCommandType.Turns,
    ["turns"] = ControlCommandType.TurnsSince,
    ["readc"] = ControlCommandType.ReadCount,
    ["rnd"] = ControlCommandType.Random,
    ["srnd"] = ControlCommandType.SeedRandom,
    ["visit"] = ControlCommandType.VisitIndex,
    ["seq"] = ControlCommandType.SequenceShuffleIndex,
    ["thread"] = ControlCommandType.StartThread,
    ["done"] = ControlCommandType.Done,
    ["end"] = ControlCommandType.End,
    ["listInt"] = ControlCommandType.ListFromInt,
    ["range"] = ControlCommandType.ListRange,
    ["lrnd"] = ControlCommandType.ListRandom,
    ["#"] = ControlCommandType.BeginTag,
    ["/#"] = ControlCommandType.EndTag,
}