return {
    [ControlCommandType.EvalStart] = "ev",
    [ControlCommandType.EvalOutput] = "out",
    [ControlCommandType.EvalEnd] = "/ev",
    [ControlCommandType.Duplicate] = "du",
    [ControlCommandType.PopEvaluatedValue] = "pop",
    [ControlCommandType.PopFunction] = "~ret",
    [ControlCommandType.PopTunnel] = "->->",
    [ControlCommandType.BeginString] = "str",
    [ControlCommandType.EndString] = "/str",
    [ControlCommandType.NoOp] = "nop",
    [ControlCommandType.ChoiceCount] = "choiceCnt",
    [ControlCommandType.Turns] = "turn",
    [ControlCommandType.TurnsSince] = "turns",
    [ControlCommandType.ReadCount] = "readc",
    [ControlCommandType.Random] = "rnd",
    [ControlCommandType.SeedRandom] = "srnd",
    [ControlCommandType.VisitIndex] = "visit",
    [ControlCommandType.SequenceShuffleIndex] = "seq",
    [ControlCommandType.StartThread] = "thread",
    [ControlCommandType.Done] = "done",
    [ControlCommandType.End] = "end",
    [ControlCommandType.ListFromInt] = "listInt",
    [ControlCommandType.ListRange] = "range",
    [ControlCommandType.ListRandom] = "lrnd",
    [ControlCommandType.BeginTag] = "#",
    [ControlCommandType.EndTag] = "/#",
}