local types = require('constants/control_commands/types')

return {
    ["ev"] = types.EvalStart,
    ["out"] = types.EvalOutput,
    ["/ev"] = types.EvalEnd,
    ["du"] = types.Duplicate,
    ["pop"] = types.PopEvaluatedValue,
    ["~ret"] = types.PopFunction,
    ["->->"] = types.PopTunnel,
    ["str"] = types.BeginString,
    ["/str"] = types.EndString,
    ["nop"] = types.NoOp,
    ["choiceCnt"] = types.ChoiceCount,
    ["turn"] = types.Turns,
    ["turns"] = types.TurnsSince,
    ["readc"] = types.ReadCount,
    ["rnd"] = types.Random,
    ["srnd"] = types.SeedRandom,
    ["visit"] = types.VisitIndex,
    ["seq"] = types.SequenceShuffleIndex,
    ["thread"] = types.StartThread,
    ["done"] = types.Done,
    ["end"] = types.End,
    ["listInt"] = types.ListFromInt,
    ["range"] = types.ListRange,
    ["lrnd"] = types.ListRandom,
    ["#"] = types.BeginTag,
    ["/#"] = types.EndTag,
}